### ISSUE TITLE
possible error when installing on v14

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/HR-Addon#22]
Installing hr_addon...

Updating DocTypes for hr_addon : [====== ] 16%An error occurred while installing hr_addon: Module import failed for Workday, the DocType you're trying to open might be deleted.
 Error: No module named 'erpnext.hr'

Traceback (most recent call last):

 File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module

 doctype_python_modules[key] = frappe.get_module(module_name)

 File "apps/frappe/frappe/__init__.py", line 1327, in get_module

 return importlib.import_module(modulename)

 File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

 return _bootstrap._gcd_import(name[level:], package, level)

 File "", line 1050, in _gcd_import

 File "", line 1027, in _find_and_load

 File "", line 1006, in _find_and_load_unlocked

 File "", line 688, in _load_unlocked

 File "", line 883, in exec_module

 File "", line 241, in _call_with_frames_removed

 File "apps/hr_addon/hr_addon/hr_addon/doctype/workday/workday.py", line 15, in 

 from erpnext.hr.utils import get_holiday_dates_for_employee, validate_active_employee

ModuleNotFoundError: No module named 'erpnext.hr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

 File "apps/frappe/frappe/commands/site.py", line 413, in install_app

 _install_app(app, verbose=context.verbose, force=force)

 File "apps/frappe/frappe/installer.py", line 294, in install_app

 sync_for(name, force=force, reset_permissions=True)

 File "apps/frappe/frappe/model/sync.py", line 80, in sync_for

 import_file_by_path(

 File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path

 import_doc(

 File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc

 doc.insert()

 File "apps/frappe/frappe/model/document.py", line 285, in insert

 self.run_post_save_methods()

 File "apps/frappe/frappe/model/document.py", line 1077, in run_post_save_methods

 self.run_method("on_update")

 File "apps/frappe/frappe/model/document.py", line 909, in run_method

 out = Document.hook(fn)(self, *args, **kwargs)

 File "apps/frappe/frappe/model/document.py", line 1259, in composer

 return composed(self, method, *args, **kwargs)

 File "apps/frappe/frappe/model/document.py", line 1241, in runner

 add_to_return_value(self, fn(self, *args, **kwargs))

 File "apps/frappe/frappe/model/document.py", line 906, in fn

 return method_object(*args, **kwargs)

 File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 408, in on_update

 self.run_module_method("on_doctype_update")

 File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 493, in run_module_method

 module = load_doctype_module(self.name, self.module)

 File "apps/frappe/frappe/modules/utils.py", line 244, in load_doctype_module

 raise ImportError(msg) from e

ImportError: Module import failed for Workday, the DocType you're trying to open might be deleted.
 Error: No module named 'erpnext.hr'

**Comment by wojosc** [comment]
@lajidey-foss this occeurs on v14 install. Possibly because there is now a new structure, as HR is not part of standard ERPNext install of v14. We have to look over this error and create a new version witch will be v14 kompatible.

Thank you in advance

**Comment by wojosc** [comment]
@lajidey-foss I get an error when trying to update on frappecloud:

bench get-app hr_addon
Getting HR-Addon
$ git clone file:///home/frappe/context/apps/hr_addon  --depth 1 --origin upstream
Cloning into 'hr_addon'...
Ignoring dependencies of file:///home/frappe/context/apps/hr_addon. To install dependencies use --resolve-deps
Installing hr_addon
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/hr_addon
ERROR: Could not find a version that satisfies the requirement hrms (from hr-addon) (from versions: none)
ERROR: No matching distribution found for hrms
ERROR:
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 573, in install_app
    bench.run(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
INFO: A newer version of bench is available: 5.15.2 → 5.16.1
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/hr_addon `#stage-apps-hr_addon`]: exit code: 1
> [stage-0 29/32] RUN --mount=type=cache,target=/home/frappe/.cache,uid=1000,gid=1000 --mount=type=bind,source=apps/hr_addon,target=/home/frappe/context/apps/hr_addon bench get-app file:///home/frappe/context/apps/hr_addon `#stage-apps-hr_addon`:
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/hr_addon `#stage-apps-hr_addon`]: exit code: 1

**Comment by lajidey-foss** [comment]
Try a fresh install based on version 14 branch
