### ISSUE TITLE
Fix: Missing dependency when installing the app

### ISSUE THREAD

**Issue by roquegv** [phamos-eu/HR-Addon#27]
When I run `bench get-app https://github.com/phamos-eu/HR-Addon.git` I get:

```
Getting HR-Addon
$ git clone https://github.com/phamos-eu/HR-Addon.git  --depth 1 --origin upstream
Cloning into 'HR-Addon'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 49 (delta 10), reused 30 (delta 3), pack-reused 0
Unpacking objects: 100% (49/49), done.

Installing hr_addon
$ ./env/bin/pip install -q -U -e ./apps/hr_addon 
ERROR: Could not find a version that satisfies the requirement hrms (from hr-addon) (from versions: none)
ERROR: No matching distribution found for hrms

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
$ bench build --app hr_addon
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/utils.py", line 42, in build
    frappe.init("")
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 248, in init
    setup_module_map()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1404, in setup_module_map
    for module in get_module_list(app):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1254, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1205, in get_module
    return importlib.import_module(modulename)
  File "/workspace/development/frappe-bench/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hr_addon'
```
Basically, it tries to install the python package `hrms`, which is defined in `requirements.txt`: 
```
# frappe -- https://github.com/frappe/frappe is installed via 'bench init'
#paytmchecksum~=1.7.0
hrms
```
But `hrms` is not a python package, so it is not possible to install it.

Partial solution for now is to remove `hrms` from requirements.txt file.

**Comment by wojosc** [comment]
are you installing this on a v13 or v14? On v13 you will have to use a differenz branch. I'm guessing `main`
![grafik](https://user-images.githubusercontent.com/22279621/236843571-8c8997d5-1f4b-4a37-9e7c-6026e7e749f4.png)

What used to be called HR in v13 is HRMS in v14...

@lajidey-foss might be able to comment on this also. He applied the fix for v14: https://github.com/phamos-eu/HR-Addon/pull/23

**Comment by roquegv** [comment]
Oh yes, I was installing this on v13.

**Comment by roquegv** [comment]
`hrms` is not a valid python package and should not go on `requirements.txt`.

This is a frappe app. In order to express the dependency of `HR-Addon` on `hrms`, it should be done using hooks.py, as follow:

`required_apps = ["hrms"]`
